// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: increment.proto

package increment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoidMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VoidMessage) Reset() {
	*x = VoidMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_increment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoidMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidMessage) ProtoMessage() {}

func (x *VoidMessage) ProtoReflect() protoreflect.Message {
	mi := &file_increment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidMessage.ProtoReflect.Descriptor instead.
func (*VoidMessage) Descriptor() ([]byte, []int) {
	return file_increment_proto_rawDescGZIP(), []int{0}
}

type IncrementMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *IncrementMessage) Reset() {
	*x = IncrementMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_increment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementMessage) ProtoMessage() {}

func (x *IncrementMessage) ProtoReflect() protoreflect.Message {
	mi := &file_increment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementMessage.ProtoReflect.Descriptor instead.
func (*IncrementMessage) Descriptor() ([]byte, []int) {
	return file_increment_proto_rawDescGZIP(), []int{1}
}

func (x *IncrementMessage) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_increment_proto protoreflect.FileDescriptor

var file_increment_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x0d, 0x0a, 0x0b,
	0x56, 0x6f, 0x69, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x10, 0x49,
	0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x56, 0x0a, 0x10, 0x49, 0x6e, 0x63, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x49,
	0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x69, 0x6e, 0x63, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x1b, 0x2e, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x63,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x65,
	0x78, 0x66, 0x61, 0x6c, 0x6c, 0x2f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x3b,
	0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_increment_proto_rawDescOnce sync.Once
	file_increment_proto_rawDescData = file_increment_proto_rawDesc
)

func file_increment_proto_rawDescGZIP() []byte {
	file_increment_proto_rawDescOnce.Do(func() {
		file_increment_proto_rawDescData = protoimpl.X.CompressGZIP(file_increment_proto_rawDescData)
	})
	return file_increment_proto_rawDescData
}

var file_increment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_increment_proto_goTypes = []interface{}{
	(*VoidMessage)(nil),      // 0: increment.VoidMessage
	(*IncrementMessage)(nil), // 1: increment.IncrementMessage
}
var file_increment_proto_depIdxs = []int32{
	0, // 0: increment.IncrementService.Increment:input_type -> increment.VoidMessage
	1, // 1: increment.IncrementService.Increment:output_type -> increment.IncrementMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_increment_proto_init() }
func file_increment_proto_init() {
	if File_increment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_increment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoidMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_increment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_increment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_increment_proto_goTypes,
		DependencyIndexes: file_increment_proto_depIdxs,
		MessageInfos:      file_increment_proto_msgTypes,
	}.Build()
	File_increment_proto = out.File
	file_increment_proto_rawDesc = nil
	file_increment_proto_goTypes = nil
	file_increment_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IncrementServiceClient is the client API for IncrementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IncrementServiceClient interface {
	Increment(ctx context.Context, in *VoidMessage, opts ...grpc.CallOption) (*IncrementMessage, error)
}

type incrementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIncrementServiceClient(cc grpc.ClientConnInterface) IncrementServiceClient {
	return &incrementServiceClient{cc}
}

func (c *incrementServiceClient) Increment(ctx context.Context, in *VoidMessage, opts ...grpc.CallOption) (*IncrementMessage, error) {
	out := new(IncrementMessage)
	err := c.cc.Invoke(ctx, "/increment.IncrementService/Increment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncrementServiceServer is the server API for IncrementService service.
type IncrementServiceServer interface {
	Increment(context.Context, *VoidMessage) (*IncrementMessage, error)
}

// UnimplementedIncrementServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIncrementServiceServer struct {
}

func (*UnimplementedIncrementServiceServer) Increment(context.Context, *VoidMessage) (*IncrementMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Increment not implemented")
}

func RegisterIncrementServiceServer(s *grpc.Server, srv IncrementServiceServer) {
	s.RegisterService(&_IncrementService_serviceDesc, srv)
}

func _IncrementService_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementServiceServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/increment.IncrementService/Increment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementServiceServer).Increment(ctx, req.(*VoidMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _IncrementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "increment.IncrementService",
	HandlerType: (*IncrementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Increment",
			Handler:    _IncrementService_Increment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "increment.proto",
}
